## SQL SERVER
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.datasource.url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/blog-engin
spring.datasource.username: root
spring.datasource.password: test001
spring.jpa.properties.hibernate.jdbc.time_zone: UTC

## BLOG PARAMETERS
blog.title: DevPub
blog.subtitle: Заметки разработчика
blog.phone: +7 (906) 764-73-71
blog.email: dkapriz@mail.ru
blog.copyright: Дмитрий Каприз
blog.copyrightFrom: 2022