## SPRING
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: true
spring.datasource.url: jdbc:${BEGET_DATABASE_URL:mysql://localhost:3306/med-blog-engine}
spring.datasource.username: ${BEGET_LOGIN}
spring.datasource.password: ${BEGET_PASSWORD}
##spring.jpa.properties.hibernate.jdbc.time_zone: UTC
spring.servlet.multipart.max-file-size: -1
spring.servlet.multipart.max-request-size: -1
server.port: ${PORT:8080}

## SPRING MAIL
spring.mail.protocol: smtps
spring.mail.host: smtp.mail.ru
spring.mail.port: 465
spring.mail.username: ${EMAIL}
spring.mail.password: ${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.ssl.enable: true
mail.debug: false

## BLOG PARAMETERS
blog.title: История и Медицина
blog.subtitle: Мой сборник статей
blog.phone: +7 (906) 777-66-66
blog.email: xxxxxxxx@mail.ru
blog.copyright: Дмитрий К.
blog.copyrightFrom: 2022

## GENERATOR CAPTCHA
config.captcha-time-live: 3600 #IN SECOND
config.captcha-height: 35 #px
config.captcha-wight: 100 #px
config.captcha-format: png
config.captcha-url: data:image/png;base64

## TIME
config.time-date-format: yyyy-MM-dd

## USER
config.user-min-length-password: 6

## POST
config.post-min-length-title: 3
config.post-min-length-text: 50
config.post-max-length-title: 500
config.post-max-length-text: 600000
config.post-max-length-announce: 150

## POST COMMENT
config.post-comment-min-length: 1
config.post-comment-max-length: 1000

## IMAGE
config.image-max-size: 1 # IN MB
config.image-format: jpg, png
config.image-path: upload
config.image-count-sub-folders: 3
config.image-count-char-in-folder-name: 2
config.image-count-char-in-file-name: 15
config.image-prefix-file-name: IMG
config.image-avatar-format: png
config.image-avatar-size: 36 #px
config.image-avatar-folder-name: usava
config.image-avatar-remove-value: 1

## MAIL
config.mail-from-user-name: pochtalion2023@mail.ru #Не должен содержать пробелы и элементы управления
config.mail-domain-name: http://localhost:8080
config.mail-change-password-sub-address: /login/change-password/
config.mail-restore-password-sub-address: /login/restore-password
config.mail-restore-password-subject: Восстановление пароля
config.mail-restore-password-msg-part-before-link: Письмо восстановления пароля сгенерировано автоматически.<br>Для восстановления перейдите по
config.mail-restore-password-msg-part-after-link: .<br>Пожалуйста не отвечайте на письмо